// Prints the current content inventory: every data pack (first-level folder
// under content/packs/) with its topic/question ids. Paste ONE pack's section
// into an external AI's context when extending THAT pack — packs are
// independent, ids only need to be unique within a pack, and a pack's
// questions may only reference its own topics (or seed taxonomy ids).
//
// With --write, saves it to docs/content-inventory.md instead (kept current
// by `npm run release:content`, so it is always linkable from GitHub).
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const PACKS_DIR = path.join(process.cwd(), "content", "packs");

const lines = [];
const emit = (s = "") => lines.push(s);
const console = { log: emit };

emit("# Existing content inventory (for AI context)");
emit("");
emit("<!-- AUTO-GENERATED by scripts/content-ids.mjs — do not edit by hand. -->");
emit("");
emit("Every data pack below is INDEPENDENT: ids are scoped to the pack, and");
emit("no pack may be thinned because another pack covers a similar concept.");
emit("");

// Seed topics are id-only taxonomy entries any pack may reference or redefine.
const seedSrc = readFileSync(
  path.join(process.cwd(), "src", "core", "seed", "topics.ts"),
  "utf-8",
);
const seedIds = [...seedSrc.matchAll(/topic\("([a-z0-9_]+)"/g)].map((m) => m[1]);
console.log(
  "## Seed topic ids (bare taxonomy — referenceable or redefinable by any pack)\n",
);
console.log(seedIds.sort().join(", ") + "\n");

for (const entry of readdirSync(PACKS_DIR).sort()) {
  const full = path.join(PACKS_DIR, entry);
  const files = statSync(full).isDirectory()
    ? readdirSync(full)
        .filter((f) => f.endsWith(".json"))
        .map((f) => ({ label: entry, file: `${entry}/${f}`, path: path.join(full, f) }))
    : entry.endsWith(".json")
      ? [{ label: entry.replace(/\.json$/, ""), file: entry, path: full }]
      : [];
  if (files.length === 0) continue;
  console.log(`# Data pack: ${files[0].label}\n`);
  for (const { file, path: fp } of files) {
    let pack;
    try {
      pack = JSON.parse(readFileSync(fp, "utf-8"));
    } catch {
      continue;
    }
    if (typeof pack.id !== "string") continue; // sidecar file
    console.log(`## File: ${file}  (pack id: ${pack.id})`);
    for (const t of pack.topics ?? []) {
      const imp = t.importance !== undefined ? ` (importance ${t.importance})` : "";
      console.log(`  topic: ${t.id} — ${t.name} [${t.category}]${imp}`);
    }
    for (const q of pack.questions ?? []) {
      console.log(`  question: ${q.id} — ${q.title} (topics: ${q.topicIds.join(", ")})`);
    }
    console.log("");
  }
}

const output = lines.join("\n");
if (process.argv.includes("--write")) {
  const target = path.join(process.cwd(), "docs", "content-inventory.md");
  writeFileSync(target, output + "\n");
  process.stdout.write(`content inventory written to docs/content-inventory.md\n`);
} else {
  process.stdout.write(output + "\n");
}
