import { describe, expect, it } from "vitest";
import { applyManualOverride, reviewAnswer } from "../answerReviewer";
import { getQuestionCard } from "@/core/seed/questions";

const NOW = "2026-07-04T00:00:00.000Z";

describe("reviewAnswer", () => {
  it("produces a full review with covered/weak/missing buckets", () => {
    const card = getQuestionCard("backend_idempotency_001")!;
    const { review, practiceItems } = reviewAnswer(
      card,
      "Idempotency means the same request multiple times has no duplicate side effect. " +
        "I would use an idempotency key generated by the client.",
      "backend_developer",
      NOW,
    );
    expect(review.coveredRubricItemIds).toContain("defines_idempotency");
    expect(review.coveredRubricItemIds).toContain("mentions_idempotency_key");
    expect(review.missingRubricItemIds).toContain("key_storage_replay");
    expect(review.totalScore).toBeGreaterThan(50);
    expect(review.totalScore).toBeLessThan(100);
    // no critical item missed → no practice items
    expect(practiceItems).toHaveLength(0);
  });

  it("generates practice items for missed critical points", () => {
    const card = getQuestionCard("backend_idempotency_001")!;
    const { review, practiceItems } = reviewAnswer(
      card,
      "I would just save the order to the database.",
      "backend_developer",
      NOW,
    );
    expect(review.missingRubricItemIds).toContain("defines_idempotency");
    expect(practiceItems.length).toBe(2);
    expect(review.generatedPracticeItems.length).toBe(2);
  });
});

describe("applyManualOverride", () => {
  it("moves the item between buckets, records the override, and rescores", () => {
    const card = getQuestionCard("backend_idempotency_001")!;
    const { review } = reviewAnswer(
      card,
      "I would just save the order to the database.",
      "backend_developer",
      NOW,
    );
    const before = review.totalScore;

    const updated = applyManualOverride(
      card,
      review,
      "defines_idempotency",
      "covered",
      "backend_developer",
    );
    expect(updated.coveredRubricItemIds).toContain("defines_idempotency");
    expect(updated.missingRubricItemIds).not.toContain("defines_idempotency");
    expect(updated.manualOverrides).toEqual([
      {
        rubricItemId: "defines_idempotency",
        previousStatus: "missing",
        newStatus: "covered",
      },
    ]);
    expect(updated.totalScore).toBeGreaterThan(before);
  });

  it("is a no-op when the status does not change", () => {
    const card = getQuestionCard("backend_idempotency_001")!;
    const { review } = reviewAnswer(card, "nothing relevant", "backend_developer", NOW);
    const updated = applyManualOverride(
      card,
      review,
      "defines_idempotency",
      "missing",
      "backend_developer",
    );
    expect(updated).toBe(review);
  });
});
