import { describe, expect, it } from "vitest";
import type { RubricItem } from "@/core/models";
import { reviewAnswerHybrid } from "../answerReviewer";
import {
  combineStatuses,
  itemCandidates,
  segmentTranscript,
  semanticSimilarities,
  statusFromSimilarity,
  type EmbedFn,
} from "../semanticMatcher";
import { getQuestionCard } from "@/core/seed/questions";

/**
 * Deterministic fake embedder: texts sharing a marker word get identical
 * vectors (cosine 1), everything else is orthogonal — lets us test the
 * pipeline without downloading the real model (which was calibrated
 * separately).
 */
const MARKERS = ["alpha", "beta", "gamma"];
function fakeEmbed(texts: string[]): Promise<number[][]> {
  return Promise.resolve(
    texts.map((t) => {
      const v = new Array(MARKERS.length + 1).fill(0);
      const idx = MARKERS.findIndex((m) => t.toLowerCase().includes(m));
      v[idx === -1 ? MARKERS.length : idx] = 1;
      // unmatched texts each get a unique-ish orthogonal-to-markers vector
      return v;
    }),
  );
}

const item = (id: string, signal: string, concept = signal): RubricItem => ({
  id,
  label: `Label ${id}`,
  description: `Description mentioning ${concept}.`,
  importance: "critical",
  roleWeight: { backend_developer: 5 },
  acceptedSignals: [signal],
});

describe("segmentTranscript", () => {
  it("splits sentences and windows long clauses", () => {
    expect(segmentTranscript("First point. Second point!")).toEqual([
      "First point",
      "Second point",
    ]);
    const long = Array.from({ length: 40 }, (_, i) => `w${i}`).join(" ");
    const segments = segmentTranscript(long);
    expect(segments.length).toBeGreaterThan(1);
  });

  it("drops one-word fragments", () => {
    expect(segmentTranscript("Yes. I would use caching.")).toEqual([
      "I would use caching",
    ]);
  });
});

describe("semanticSimilarities", () => {
  it("scores items by best segment↔candidate similarity", async () => {
    const items = [item("a", "alpha"), item("b", "beta")];
    const sims = await semanticSimilarities(
      "we definitely handle alpha here. something unrelated.",
      items,
      fakeEmbed as EmbedFn,
    );
    expect(sims.get("a")).toBeCloseTo(1);
    expect(sims.get("b")).toBeCloseTo(0);
  });
});

describe("status combination", () => {
  it("maps similarity to status by calibrated thresholds", () => {
    expect(statusFromSimilarity(0.7)).toBe("covered");
    expect(statusFromSimilarity(0.5)).toBe("weak");
    expect(statusFromSimilarity(0.3)).toBe("missing");
  });

  it("takes the stronger verdict and caps negatives at weak", () => {
    expect(combineStatuses("missing", "covered", false)).toBe("covered");
    expect(combineStatuses("covered", "missing", false)).toBe("covered");
    expect(combineStatuses("weak", "missing", false)).toBe("weak");
    expect(combineStatuses("missing", "covered", true)).toBe("weak");
  });

  it("itemCandidates exposes concept text and signals", () => {
    const cands = itemCandidates(item("a", "alpha"));
    expect(cands[0]).toBe("Label a. Description mentioning alpha.");
    expect(cands).toContain("alpha");
  });
});

describe("reviewAnswerHybrid", () => {
  const NOW = "2026-07-05T00:00:00.000Z";

  it("upgrades paraphrased points and marks them as semantic", async () => {
    const card = {
      ...getQuestionCard("backend_idempotency_001")!,
      // signal "zebraword" never appears in the answer — only the concept
      // text (description) is semantically close, like a real paraphrase.
      expectedPoints: [item("para", "zebraword", "alpha"), item("miss", "beta")],
    };
    const { review } = await reviewAnswerHybrid(
      card,
      "my answer talks about alpha in other words entirely.",
      "backend_developer",
      NOW,
      fakeEmbed as EmbedFn,
    );
    expect(review.coveredRubricItemIds).toContain("para");
    expect(review.semanticUpgradedIds).toEqual(["para"]);
    expect(review.missingRubricItemIds).toContain("miss");
  });

  it("keyword matches never get downgraded by low similarity", async () => {
    const card = {
      ...getQuestionCard("backend_idempotency_001")!,
      expectedPoints: [item("kw", "idempotency key")],
    };
    const { review } = await reviewAnswerHybrid(
      card,
      "I would use an idempotency key.",
      "backend_developer",
      NOW,
      fakeEmbed as EmbedFn,
    );
    expect(review.coveredRubricItemIds).toEqual(["kw"]);
    expect(review.semanticUpgradedIds).toEqual([]);
  });

  it("falls back to keyword-only when embedding fails", async () => {
    const card = getQuestionCard("backend_idempotency_001")!;
    const failingEmbed: EmbedFn = () => Promise.reject(new Error("no model"));
    const { review } = await reviewAnswerHybrid(
      card,
      "I would use an idempotency key generated by the client.",
      "backend_developer",
      NOW,
      failingEmbed,
    );
    expect(review.coveredRubricItemIds).toContain("mentions_idempotency_key");
    expect(review.semanticUpgradedIds).toEqual([]);
  });
});
